name: eclipse_test
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  meta: ^1.9.1
  retrofit: ^4.0.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  lint: ^2.1.2
  retrofit_generator: ^8.0.3

flutter:
  uses-material-design: true
